name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
      
      - name: Deploy to prod branch (overwrite)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin prod
          git checkout prod || git checkout -b prod
          git rm -rf .       # prod branch'teki tüm dosyaları sil
          cp -r dist/* .     # dist içeriğini prod branch root'una kopyala
          git add .
          git commit -m "Deploy" || echo "No changes to commit"
          git push origin prod --force
